# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-paginate

  
# Site settings
title: "Fernando Ipar"
description: >  # this means to ignore newlines until "email:"
   Thoughts on technology, databases, and whatever comes to mind 

email: fipar (at) acm (dot) org 
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
#cover: "https://www.dropbox.com/s/ei6zmkeypujmwfj/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg" 
cover: "/assets/images/horizon.jpg"

name: 'Fernando Ipar'
author: 'Fernando Ipar'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://fernandoipar.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/fipar
#    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
